name: errandmate
version: 1.0.0+1
publish_to: none
description: A Freelance Errand App
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  get: 4.6.5
  flutter: 
    sdk: flutter
  introduction_screen: ^3.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
